### ISSUE TITLE
iFrame missing css

### ISSUE THREAD

**Issue by esetnik** [percy/cli#1189]
## The problem

After upgrading to v1.19.2 the snapshots of iframed content does not render any CSS.

See https://percy.io/283b5e1b/ProdigyEMS/builds/25284757/changed/1410160725?browser=chrome&browser_ids=33%2C34&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280

## Environment

- Node version:
- `@percy/cli` version: v1.19.2
- Version of Percy SDK you’re using: @percy/cypress v3.1.2
- If needed, a build or snapshot ID: 25284757
- OS version: linux
- Type of shell command-line [interface]: sh

## Details

I believe it could be related to #1165

## Debug logs

If you are reporting a bug, _always_ include logs! [Give the "Debugging SDKs"
document a quick read for how to gather logs](https://docs.percy.io/docs/debugging-sdks#debugging-sdks)

Please do not trim or edit these logs, often times there are hints in the full
logs that help debug what is going on.

## Code to reproduce issue

Given the nature of testing/environment bugs, it’s best to try and isolate the
issue in a reproducible repo. This will make it much easier for us to diagnose
and fix.

**Comment by itsjwala** [comment]
Hey @esetnik 👋 

I checked the build and could see the style sheets are being discovered as `text/html`  instead of `text/css`  causing it to not load it.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/24763310/220417671-1146cf0c-f223-469f-9975-4a26e0e53b45.png">
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/24763310/220417872-6f307aa6-aad8-4932-84f0-3ed94affccd0.png">

you can verify it on your end by checking `--verbose` logs of the CLI for asset discovery browser.

**Comment by esetnik** [comment]
@itsjwala but those paths are not the correct paths to the css files in the iframe. It looks like percy is rewriting the paths for iframed content for some reason to use a relative path on the parent page. This is new behavior as of v1.19.2 (the iframed snapshots are working correctly in real tests as well as in percy v1.18.0 and earlier).

**Comment by esetnik** [comment]
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/664434/220421719-5334e831-0db7-4db6-8dfc-0146720e8c7b.png">

**Comment by itsjwala** [comment]
@esetnik 
* yes we override the parent base URL with our own domain, but the iframe URL for the styles seems to be the same for `styles.css`
* The point being that those assets are being discovered as `text/html` - can you please share verbose logs in this case for us to debug better?

**Comment by esetnik** [comment]
> @esetnik
> 
> * yes we override the parent base URL with our own domain, but the iframe URL for the styles seems to be the same for `styles.css`
> 

I'm not understanding what you mean by this. Percy is using the domain https://frontend.local.prodigyems.com to resolve those assets but they are actually hosted under https://local.prodigyems.com. See my screenshot above. The url is `https://local.prodigyems.com/css/line-icons/style.css` not `https://frontend.local.prodigyems.com/css/line-icons/style.css` and they do return the correct `content-type` header.

**Comment by itsjwala** [comment]
Hey @esetnik 
* I was talking about the base url ( `proxyme.percy.io` which we use instead of any localhost domain)
> We've not changed this behavior - it's the same [ref](https://github.com/percy/cli/blob/master/packages/dom/src/serialize-frames.js#L3-L13).
* Apologies, I see the issue now - though there wasn't any change around this bit ^
* I'm trying to create a repro on my end for this issue, please allow me some time to check this further.
