### ISSUE TITLE
NPM Error due to transitive dependency on chalk : No matching version found for chalk@4.1.1.

### ISSUE THREAD

**Issue by GauriBhutkar** [percy/cli#313]
This was working find till chalk@4.1.0. Chalk people recently upgraded to version 4.1.1 and percy/cli started failing with this new version. Error - `No matching version found for chalk@4.1.1.`
Raising the issue here as I could find the package on package published on npm.

**Comment by wwilsman** [comment]
Hey @GauriBhutkar, this doesn't appear to be a Percy issue, but rather a dependency resolution issue. I'm able to update the lockfile to chalk 4.1.1 which installs fine since it exists on the registry. Perhaps there is something going on with your machine/network such as cache/proxy issues preventing that version from resolving?
