### ISSUE TITLE
execute in YAML doesn't work in additionalSnapshots

### ISSUE THREAD

**Issue by cancan101** [percy/cli#600]
## The problem

An `execute` function specified in YAML for `additionalSnapshots` does not get run.

## Environment

- Node version: `v15.4.0`
- `@percy/cli` version: `@percy/cli@^1.0.0-beta.70`
- OS version: `macOS`

## Details

There seems to be a regression of: https://github.com/percy/cli/issues/392 where an execute function passed to `additionalSnapshots` is not being run. I am using a yaml file for specifying the snapshots + the execute function definitions. I believe this is because the the value passed execute is not being mapped to a sub key of `beforeSnapshot` as it should be. I can manually do this in the yaml file but then I get a warning: 
```
Invalid snapshot options:
```
as that type is not allowed for in the types defintion:
https://github.com/percy/cli/blob/ceadd44a520750782f6c72197457b4514370a785/packages/core/src/config.js#L183

## Debug logs
When I put a 3s delay in that execute function, I expect to see something like this:
```
[percy:core:network] Wait for 100ms idle (3100ms)
```
however when the function does run, I see:
```
[percy:core:network] Wait for 100ms idle (100ms)
```

**Comment by cancan101** [comment]
I think that test is insufficient because you handle functions differently from strings / objects: https://github.com/percy/cli/blob/6e275ce6efe250c52550d4e9ef6991effee4e2d1/packages/core/src/page.js#L185-L186

in the documented case of the  `execute` for `additionalSnapshots`, it will either be a function (as in test and fine) or a `string`. In the string case you will attempt to optionally deference `beforeSnapshot` which will not work.

**Comment by cancan101** [comment]
i believe this issue still exists.

**Comment by wwilsman** [comment]
Sorry for the radio silence on this! You were absolutely right that there was some missing logic in the page execute method. Although the object syntax is only transformed for top-level snapshots (not additional snapshots) as specified by the schema. So the fix was to simply adjust the logic within that page execute method that you pointed out!

The merged fix should be released within the next few days, or next week at the latest

**Comment by patricknelson** [comment]
Actually, I'm coming from #513 and just seeing this, since I'm trying to run `execute.afterResize` in this `additionalSnapshots` parameter. I'm having a very difficult time finding complete documentation on all of the YAML parameters.

So, am I to infer that, since `execute` should support `afterResize` and that `additionalSnapshots` supports `execute` that by extension `additionalSnapshots.execute.afterResize` should **also** work? This isn't clear in the documentation. 😕
